# Generated by Django 5.2.3 on 2025-07-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyModel',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('Subject', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('roll_no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('course', models.CharField(max_length=25)),
                ('marks', models.FloatField()),
            ],
        ),
    ]
