# Generated by Django 5.2.3 on 2025-07-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('author', models.CharField(max_length=25)),
                ('publication_date', models.DateField()),
            ],
        ),
    ]
